/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../hdl/output/tmr/test_VTRTMR.v                                                        *
 *                                                                                                  *
 * user    : lucas                                                                                  *
 * host    : DESKTOP-BFDSFP2                                                                        *
 * date    : 06/03/2023 10:54:38                                                                    *
 *                                                                                                  *
 * workdir : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg_cfg_gen/config            *
 * cmd     : /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg-master/bin/tmrg -c tmrg.cfg *
 *           -vv                                                                                    *
 * tmrg rev: 8866e6fc289c280025f682412a4717092ab6238b                                               *
 *                                                                                                  *
 * src file: ../hdl/output/test_VTR.v                                                               *
 *           Git SHA           : 8866e6fc289c280025f682412a4717092ab6238b (?? ../hdl/output/test_VTR.v) *
 *           Modification time : 2023-03-03 23:40:54.800721                                         *
 *           File Size         : 416                                                                *
 *           MD5 hash          : 510cb21c0c5858fc2523e3c0a9558ff2                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module testTMR(
  input  clk ,
  input  d ,
  output  q 
);
wire [0:0] reg1VC;
wire [0:0] reg1VB;
wire [0:0] reg1VA;
wire [0:0] reg0VC;
wire [0:0] reg0VB;
wire [0:0] reg0VA;
wire dC;
wire dB;
wire dA;
wire clkC;
wire clkB;
wire clkA;
wor reg2TmrError;
wire reg2;
wor reg1TmrError;
wire reg1;
wor reg0TmrError;
wire reg0;
reg  reg0A ;
reg  reg0B ;
reg  reg0C ;
reg  reg1A ;
reg  reg1B ;
reg  reg1C ;
reg  reg2A ;
reg  reg2B ;
reg  reg2C ;
wire [0:0] reg2V =  reg2;
wire [0:0] reg1V =  reg1;
wire [0:0] reg0V =  reg0;

always @( posedge clkA )
  begin
    reg0A <= dA;
    reg1A <= reg0VA;
    reg2A <= reg1VA;
  end

always @( posedge clkB )
  begin
    reg0B <= dB;
    reg1B <= reg0VB;
    reg2B <= reg1VB;
  end

always @( posedge clkC )
  begin
    reg0C <= dC;
    reg1C <= reg0VC;
    reg2C <= reg1VC;
  end
assign q =  reg2V;

majorityVoter reg0Voter (
    .inA(reg0A),
    .inB(reg0B),
    .inC(reg0C),
    .out(reg0),
    .tmrErr(reg0TmrError)
    );

majorityVoter reg1Voter (
    .inA(reg1A),
    .inB(reg1B),
    .inC(reg1C),
    .out(reg1),
    .tmrErr(reg1TmrError)
    );

majorityVoter reg2Voter (
    .inA(reg2A),
    .inB(reg2B),
    .inC(reg2C),
    .out(reg2),
    .tmrErr(reg2TmrError)
    );

fanout clkFanout (
    .in(clk),
    .outA(clkA),
    .outB(clkB),
    .outC(clkC)
    );

fanout dFanout (
    .in(d),
    .outA(dA),
    .outB(dB),
    .outC(dC)
    );

fanout reg0VFanout (
    .in(reg0V),
    .outA(reg0VA),
    .outB(reg0VB),
    .outC(reg0VC)
    );

fanout reg1VFanout (
    .in(reg1V),
    .outA(reg1VA),
    .outB(reg1VB),
    .outC(reg1VC)
    );
endmodule



// /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg-master/tmrg/../common/voter.v
module majorityVoter #(
  parameter WIDTH = 1
)( 
  input wire  [WIDTH-1:0] inA,
  input wire  [WIDTH-1:0] inB,
  input wire  [WIDTH-1:0] inC,
  output wire [WIDTH-1:0] out,
  output reg              tmrErr
);
  assign out = (inA&inB) | (inA&inC) | (inB&inC);
  'ifdef tmrErr
  always @(inA or inB or inC) begin
    if (inA!=inB || inA!=inC || inB!=inC)
      tmrErr = 1;
    else
      tmrErr = 0;
  end
  'endif
endmodule


// /mnt/c/Users/Lucas/Documents/GitHub/mopshub_triplicated/tmrg-master/tmrg/../common/fanout.v
module fanout #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] in,
  output wire [WIDTH-1:0] outA,
  output wire [WIDTH-1:0] outB,
  output wire [WIDTH-1:0] outC
);
  assign outA = in;
  assign outB = in;
  assign outC = in;
endmodule
