# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4962-hoerni.fb3.fh-dortmund.de/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Accumulator_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Add_PID_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/CLK_Counter_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Control_FSM_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Control_Sys_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Diff_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Ftrim_En_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Multi_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Multi_i_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Output_Scaling_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/PID_Regler_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/Phasenfehler_Reg_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/accmaskreg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/biterrordetect2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/bittime2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/bittiming2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/counter2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/decapsulation2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/destuffing2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/edgepuffer2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/encapsulation2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/equal_id2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/erbcount2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/fastshift2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/faultfsm2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/fce2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/fsm_register2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/generalregister2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/interruptregister2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/interruptunit2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/iocpuavalon2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/llc2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/llc_fsm2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/mac2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/macfsm2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/meslencompare2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/multiplexeravalon2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/prescale2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/prescalereg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/rcrc_cell2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/rcrc_top2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/read_mux2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/ready_counter_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/rec2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/recarbitreg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/recmescontrolreg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/recmeslen2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/recregister2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/reset_mac2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/resetgen2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/rshift_cell2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/rshift_top2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/smpldbit_reg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/stuffing2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/sum2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tcrc_cell2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tcrc_top2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tec2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/timecount2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/transmesconreg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/transmitreg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tseg_reg2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tshift_cell2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/tshift_top2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/write_demux2_VTRTMR.v
      /user/lschreiter/canakari/canakari_tmr_mopshub/canakari_tmr_mopshub.srcs/sources_1/imports/tmr/can2_VTRTMR.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top can2TMR
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4962-hoerni.fb3.fh-dortmund.de/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
